on: create

jobs:
  featurePR:
    if: ${{ contains(github.ref, 'refs/heads/feature') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "master"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: ${{ github.event.commits[0].message }}
          # pr_label: prelive

  fixPR:
    if: ${{ contains(github.ref, 'refs/heads/fix') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "master"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: ${{ github.event.commits[0].message }}
          pr_label: develop
